version: "3.8"

services:
  sim:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - USER_ID=${USER_ID:-1000}
        - GROUP_ID=${GROUP_ID:-1000}
    image: ha/ros2-jazzy-sim:local
    container_name: ha_local_sim
    network_mode: host
    stdin_open: true
    tty: true
    privileged: true
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - TERM=xterm-256color
      - ROS_DOMAIN_ID=${ROS_DOMAIN_ID:-0}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ${XAUTHORITY:-$HOME/.Xauthority}:/home/ros/.Xauthority:ro
      - ./ws/src:/home/ros/ws/src:rw
      - ./data:/home/ros/data:rw
      - /dev:/dev
      - /dev/bus:/dev/bus:ro
      - /dev/serial:/dev/serial:ro
